from enum import Enum


class EnvironmentKeys(Enum):
    DISCORD_BOT_TOKEN = "DISCORD_BOT_TOKEN"
    OPEN_AI_KEY = "OPEN_AI_KEY"
    ASTRA_DB_TOKEN = "ASTRA_DB_TOKEN"
    ASTRA_DB_ENDPOINT = "ASTRA_DB_ENDPOINT"
