version: "3.8"

services:
  discord-bot:
    build: .
    container_name: discord-bot
    restart: always
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - OPEN_AI_KEY=${OPEN_AI_KEY}
      - ASTRA_DB_TOKEN = ${ASTRA_DB_TOKEN}
      - ASTRA_DB_ENDPOINT = ${ASTRA_DB_ENDPOINT}
